name: Mirror to Gitee Repo

on: [ push, delete, create ]

# Ensures that only one mirror task will run at a time.
concurrency:
  group: git-mirror

jobs:
  git-mirror:
    if: github.repository_owner == 'ixsluo'
    runs-on: ubuntu-latest
    steps:
      - uses: wearerequired/git-mirror-action@v1
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SYNC_GITEE_PRIVATE_KEY }}
        with:
          source-repo: "https://github.com/ixsluo/Crystal_DAkit.git"
          destination-repo: "git@gitee.com:xiaoshan-luo/crystal_dakit.git"
